# -*- coding: utf-8 -*-
"""travel_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117yOtqFesypHfk0OfgExqmgYA36O8fBY
"""

!pip install -q transformers torch langgraph tavily-python python-dotenv

# Commented out IPython magic to ensure Python compatibility.
# %%writefile helper_func.py
# import json, re
# 
# def clean_itinerary(text: str) -> str:
#     text = re.sub(r"\s+", " ", text)
#     text = re.sub(r"(Day\s*\d+)", r"\n\n### \1", text)
#     text = text.replace("Morning:", "\n- Morning:")
#     text = text.replace("Afternoon:", "\n- Afternoon:")
#     text = text.replace("Evening:", "\n- Evening:")
#     return text.strip()
# 
# def clean_weather(raw_weather):
#     return raw_weather
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile llm.py
# from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
# 
# MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# 
# tokenizer = AutoTokenizer.from_pretrained(MODEL)
# model = AutoModelForCausalLM.from_pretrained(MODEL)
# 
# pipe = pipeline(
#     "text-generation",
#     model=model,
#     tokenizer=tokenizer,
#     max_new_tokens=400,
#     temperature=0.6,
#     top_p=0.9,
#     do_sample=True
# )
# 
# def llm(prompt: str):
# 
#     chat = f"""
# <|system|>
# You are a travel planner.
# 
# Always output:
# 
# ### Day 1
# - Morning:
# - Afternoon:
# - Evening:
# 
# ### Day 2
# - Morning:
# - Afternoon:
# - Evening:
# 
# ### Day 3
# - Morning:
# - Afternoon:
# - Evening:
# 
# <|user|>
# {prompt}
# <|assistant|>
# """
# 
#     return pipe(chat, return_full_text=False)[0]["generated_text"]
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile workflow.py
# from langgraph.graph import StateGraph, END
# from tavily import TavilyClient
# from typing import TypedDict
# from llm import llm
# import os
# 
# class TravelPlanState(TypedDict):
#     preferences: dict
#     destination_info: str
#     itinerary: str
#     weather: str
# 
# tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))
# 
# def gather_preferences(state):
#     return {"preferences": state["preferences"]}
# 
# def fetch_destination_info(state):
# 
#     dest = state["preferences"]["destination"]
# 
#     info = tavily.search(
#         query=f"Top tourist places in {dest} city India",
#         max_results=2
#     )
# 
#     snippets=[]
#     for r in info.get("results",[]):
#         snippets.append(r["content"])
# 
#     return {"destination_info": " ".join(snippets)[:300]}
# 
# def generate_itinerary(state):
# 
#     prompt = f"""
# Create 3 day itinerary for {state['preferences']['destination']}.
# Budget {state['preferences']['budget']}.
# Interests {state['preferences']['interests']}.
# 
# Reference:
# {state['destination_info']}
# """
# 
#     return {"itinerary": llm(prompt)}
# 
# def check_weather(state):
# 
#     info = tavily.search(
#         query=f"current weather in {state['preferences']['destination']} India",
#         max_results=1
#     )
# 
#     weather = info["results"][0]["content"] if info.get("results") else "No weather"
# 
#     return {"weather": weather}
# 
# workflow = StateGraph(TravelPlanState)
# 
# workflow.add_node("prefs", gather_preferences)
# workflow.add_node("info", fetch_destination_info)
# workflow.add_node("itinerary", generate_itinerary)
# workflow.add_node("weather", check_weather)
# 
# workflow.set_entry_point("prefs")
# workflow.add_edge("prefs","info")
# workflow.add_edge("info","itinerary")
# workflow.add_edge("itinerary","weather")
# workflow.add_edge("weather", END)
# 
# app = workflow.compile()
#

import os
os.environ["TAVILY_API_KEY"] = "api-key"

from workflow import app
from helper_func import clean_itinerary, clean_weather

preferences = {
    "destination": "Delhi",
    "budget": 1000,
    "interests": ["art","food"],
    "dates": "2026-04-01 to 2026-04-03"
}

result = app.invoke({"preferences": preferences})

print("\n===== ITINERARY =====\n")
print(clean_itinerary(result["itinerary"]))

print("\n===== WEATHER =====\n")
print(clean_weather(result["weather"]))

